# Generated by Django 3.1 on 2020-10-10 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orders_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
